//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelOwner
    {
        public int HotelUserKey { get; set; }
        public string HotelUserName { get; set; }
        public string Password { get; set; }
        public System.DateTime InsertedDate { get; set; }
    }
}
