//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomCustomerMap
    {
        public int Id { get; set; }
        public int RoomKey { get; set; }
        public int CustomerKey { get; set; }
        public System.DateTime BookedTime { get; set; }
        public System.DateTime InsertedDate { get; set; }
    
        public virtual CustomerInfo CustomerInfo { get; set; }
        public virtual HotelRoom HotelRoom { get; set; }
    }
}
